name: Bug Report
description: Report a bug in the Angular Material Dev websites

body:
  - type: dropdown
    id: affected-sites
    attributes:
      label: Which site is the source of the bug?
      options:
        - angular-material.dev
        - themes.angular-material.dev
        - ui.angular-material.dev
      multiple: false
    validations:
      required: true

  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in
      render: true
      placeholder: |
        OS: linux x64
        Browser: Chrome

  - type: textarea
    id: other
    attributes:
      label: Anything else?
